/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaacademico.visao;

import java.util.ArrayList;
import java.util.HashMap;
import sistemaacademico.controle.ControleColaborador;
import sistemaacademico.controle.ControleTipoTrabalho;

/**
 *
 * @author Marlysson
 */
public class VisaoTarefa extends javax.swing.JFrame {

    private HashMap<Integer, String> codToColab;
    private HashMap<Integer, String> codToTipo;
    private HashMap<String, Integer> colabToCod;
    private HashMap<String, Integer> tipoToCod;

    /**
     * Creates new form VisaoTarefa
     */
    public VisaoTarefa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTituloTarefa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelPrincipalTarefa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textHoraInicio = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        textHoraFim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboColaboradores = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        taObservacao = new javax.swing.JEditorPane();
        btnNovoTipoTrab = new javax.swing.JButton();
        btnEditarTipoTrab = new javax.swing.JButton();
        btnGravarTipoTrab = new javax.swing.JButton();
        btnCancelarTipoTrab = new javax.swing.JButton();
        btnExcluirTipoTrab = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTarefas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelTituloTarefa.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tarefa");

        javax.swing.GroupLayout jPanelTituloTarefaLayout = new javax.swing.GroupLayout(jPanelTituloTarefa);
        jPanelTituloTarefa.setLayout(jPanelTituloTarefaLayout);
        jPanelTituloTarefaLayout.setHorizontalGroup(
            jPanelTituloTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloTarefaLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTituloTarefaLayout.setVerticalGroup(
            jPanelTituloTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloTarefaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("Código");

        jLabel3.setText("Hora Inicio");

        jLabel4.setText("Hora Fim");

        jLabel5.setText("Tipo de Tarefa");

        jLabel6.setText("Observação");

        jLabel7.setText("Colaborador");

        jScrollPane3.setHorizontalScrollBar(null);
        jScrollPane3.setViewportView(taObservacao);

        javax.swing.GroupLayout jPanelPrincipalTarefaLayout = new javax.swing.GroupLayout(jPanelPrincipalTarefa);
        jPanelPrincipalTarefa.setLayout(jPanelPrincipalTarefaLayout);
        jPanelPrincipalTarefaLayout.setHorizontalGroup(
            jPanelPrincipalTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrincipalTarefaLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalTarefaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanelPrincipalTarefaLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalTarefaLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(3, 3, 3)))
                        .addGroup(jPanelPrincipalTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textHoraFim)
                            .addComponent(comboTipo, 0, 199, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelPrincipalTarefaLayout.setVerticalGroup(
            jPanelPrincipalTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnNovoTipoTrab.setText("Novo");

        btnEditarTipoTrab.setText("Editar");

        btnGravarTipoTrab.setText("Gravar");

        btnCancelarTipoTrab.setText("Cancelar");

        btnExcluirTipoTrab.setText("Excluir");

        tableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Hora Inicio", "Hora Fim", "Tipo Tarefa", "Observacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTarefas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTituloTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPrincipalTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovoTipoTrab)
                        .addGap(65, 65, 65)
                        .addComponent(btnEditarTipoTrab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGravarTipoTrab)
                        .addGap(62, 62, 62)
                        .addComponent(btnCancelarTipoTrab)
                        .addGap(78, 78, 78)
                        .addComponent(btnExcluirTipoTrab))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTituloTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipalTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoTipoTrab)
                    .addComponent(btnEditarTipoTrab)
                    .addComponent(btnGravarTipoTrab)
                    .addComponent(btnCancelarTipoTrab)
                    .addComponent(btnExcluirTipoTrab))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        initTiposTrabalho();
        initColaboradores();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTipoTrab;
    private javax.swing.JButton btnEditarTipoTrab;
    private javax.swing.JButton btnExcluirTipoTrab;
    private javax.swing.JButton btnGravarTipoTrab;
    private javax.swing.JButton btnNovoTipoTrab;
    private javax.swing.JComboBox<String> comboColaboradores;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelPrincipalTarefa;
    private javax.swing.JPanel jPanelTituloTarefa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JEditorPane taObservacao;
    private javax.swing.JTable tableTarefas;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textHoraFim;
    private javax.swing.JFormattedTextField textHoraInicio;
    // End of variables declaration//GEN-END:variables

    private void initColaboradores() {
        codToColab = new HashMap<>();
        colabToCod = new HashMap<>();
        ArrayList<HashMap<String, Object>> colaboradores = ControleColaborador.recuperarTodos();

        for (HashMap<String, Object> c : colaboradores) {
            codToColab.put((Integer) c.get("codigo"), (String) c.get("nome"));
            colabToCod.put((String) c.get("nome"), (Integer) c.get("codigo"));
        }
    }

    private void initTiposTrabalho() {
        codToTipo = new HashMap<>();
        tipoToCod = new HashMap<>();
        ArrayList<HashMap<String, Object>> tipos = ControleTipoTrabalho.recuperarTodos();

        for (HashMap<String, Object> t : tipos) {
            codToTipo.put((Integer) t.get("codigo"), (String) t.get("descricao"));
            tipoToCod.put((String) t.get("descricao"), (Integer) t.get("codigo"));
        }
    }
}
